heat_template_version: 2014-10-16

description: |
  Deploy Nginx server with Salt

parameters:

  servers:
    type: json

resources:

  nginx_config:
    type: OS::Heat::SoftwareConfig
    properties:
      group: salt
      config: |
        nginx:\n  pkg.installed\n  service.running
          
  deploy_nginx:
    type: OS::Heat::SoftwareDeploymentGroup
    properties:
      signal_transport: TEMP_URL_SIGNAL
      config:
        get_resource: nginx_config
      servers:
        get_param: servers

outputs:
  stdout:
    description: Salt Output
    value:
      get_attr: [ deploy_nginx, deploy_stdout ]
  stderr:
    description: Salt Error Output
    value:
      get_attr: [ deploy_nginx, deploy_stderr ]
  status_code:
    description: Exit Code
    value:
      get_attr: [ deploy_nginx, deploy_status_code ]
